### ISSUE TITLE
Editor broken on Android

### ISSUE THREAD

**Issue by odinuge** [webkom/lego-editor#293]
😢

https://user-images.githubusercontent.com/1467188/106620670-13ee6600-6572-11eb-8535-66b8d8da47d1.mp4

**Comment by LudvigHz** [comment]
This is not an issue with the editor itself, but rather the implementation used with redux-form. There is an issue for lego-webapp: https://github.com/webkom/lego/issues/1383

I'm not really sure if we can do anything about this here, or if it has to be fixed in lego-webapp (which is what I'm guessing), so I'll leave it open for now.

**Comment by odinuge** [comment]
The example is buggy too tho.

https://user-images.githubusercontent.com/1467188/106731110-66319480-660f-11eb-99d5-903f4d150ae9.mp4

Also, doesnt redux-form work similar on mobile as on desktop, or haven't we examined what is causing the issue?

**Comment by LudvigHz** [comment]
> The example is buggy too tho.
Hmm, it seems you are indeed correct. It's not as noticeable it seems, but still an issue :thinking:. That's probably why I haven't noticed it.

> Also, doesnt redux-form work similar on mobile as on desktop, or haven't we examined what is causing the issue?

I don't remember quite, but when I tested this issue some time ago, I believe removing redux-form handlers improved the situation quite a lot. I'll have to look into this some more, but it seems like this happens whenever you add event handlers, so there is probably some event leaking on mobile causing issues. (The example app has an onChange handler that just console.logs). So the reason this only happens on mobile is probably due to the differences in how mobile/desktop handle input events.

**Comment by LudvigHz** [comment]
I'm now pretty sure we cannot fix this, and that it has to be implemented by slate.js. There seems to be very active development on android support though (https://github.com/ianstormtaylor/slate/issues/3786), so hopefully we can get the fix soon. (We would have to upgrade slate though :tired_face:
